messages:
  basename: messages
  fallback-to-system-locale: true
  default:
    country: BR
    language: PT

server:
  port: ${PORT:8761}
  compression:
    enabled: true
    mime-types: application/json

eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 15
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      enable-self-preservation: false
      waitTimeInMsWhenSyncEmpty: 0
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  http:
    converters:
      preferred-json-mapper: jackson
